Cine/urls.py
from django.urls import path, include

from Cine.views import GeneroList, IdiomaList, PeliculaList, GeneroDetail
from . import views

urlpatterns = [
    path('', views.Home, name='home'),
    path('about/', views.About, name='about'),
    path('votacionestreno/', views.VotacionEstreno, name='votacionestreno'),

    #serializer
    path('genero/', views.GeneroList.as_view(), name='genero_list'),
    path('genero/<int:pk>/', views.GeneroDetail.as_view()),
    path('idioma/', IdiomaList.as_view(), name='idioma_list'),
    path('idioma/<int:pk>/', views.IdiomaDetail.as_view()),
    path('pelicula/', PeliculaList.as_view(), name='pelicula_list'),
    path('pelicula/<int:pk>/', views.PeliculaDetail.as_view()),

    path('detalle/<int:id>', views.Detalle, name='detalle'),
    path('detallefunciones/<int:id>/<int:idCine>', views.Detallefunciones, name='detallefunciones'),
    path('detalleestrenos/<int:id>/<int:idCine>', views.Detalleestrenos, name='detalleestrenos'),
    path('like/<int:id>/<int:idCine>', views.Like, name='like'),
    path('votar/<int:id>/<int:idCine>', views.Votar, name='votar'),

    path('administrar/', views.Administrar, name='administrar'),

    path('denuncia/<int:id>', views.Denuncias, name='denuncia'),

    path('administrarDenunciaComentarios/', views.administrarDenunciaComentarios, name='administrarDenunciaComentarios'),
    path('mostrardenuncias/<int:id>', views.mostrardenuncias, name='mostrardenuncias'),
    path('estadocomentario/<int:id>', views.estadocomentario, name='estadocomentario'),


    path('administrarpelicula/', views.AdministarPelicula, name='administrarpelicula'),
    path('crearpelicula/', views.CrearPelicula, name='crearpelicula'),
    path('editarpelicula/<int:id>', views.EditarPelicula, name='editarpelicula'),
    path('eliminarpelicula/<int:id>', views.EliminarPelicula, name='eliminarpelicula'),

    path('administrargenero/', views.AdministarGenero, name='administrargenero'),
    path('creargenero/', views.CrearGenero, name='creargenero'),
    path('editargenero/<int:id>', views.EditarGenero, name='editargenero'),
    path('eliminargenero/<int:id>', views.EliminarGenero, name='eliminargenero'),

    path('administraridioma/', views.AdministarIdioma, name='administraridioma'),
    path('crearidioma/', views.CrearIdioma, name='crearidioma'),
    path('editaridioma/<int:id>', views.EditarIdioma, name='editaridioma'),
    path('eliminaridioma/<int:id>', views.EliminarIdioma, name='eliminaridioma'),

    path('administrarcine/', views.AdministarCine, name='administrarcine'),
    path('crearcine/', views.CrearCine, name='crearcine'),
    path('editarcine/<int:id>', views.EditarCine, name='editarcine'),
    path('eliminarcine/<int:id>', views.EliminarCine, name='eliminarcine'),

    path('administrarfuncion/', views.AdministarFuncion, name='administrarfuncion'),
    path('crearfuncion/', views.CrearFuncion, name='crearfuncion'),
    path('editarfuncion/<int:id>', views.EditarFuncion, name='editarfuncion'),
    path('eliminarfuncion/<int:id>', views.EliminarFuncion, name='eliminarfuncion'),

    path('mostrarcine/<int:id>', views.MostrarCine, name='mostrarcine'),
    path('mostrarfunciones/<int:id>', views.MostrarFunciones, name='mostrarfunciones'),
    path('mostrarpeliculas/<int:id>', views.MostrarPeliculas, name='mostrarpeliculas'),

]

WebCine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#token api
#from rest_framework.authtoken import views
#from Cine.views import Login, Logout

from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('', include('Cine.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('registration.backends.default.urls')),
    path('select2/', include('django_select2.urls')),
    path('api/', include(('Cine.urls', 'api'))),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth')


    #path('api_generate_token/', views.obtain_auth_token),
    #path('login/', Login.as_view(), name='login'),
    #path('logout/', Logout.as_view(), name='logout'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#personalizacion de los titulos del adminsitrador de django
admin.site.site_header = "Administracion de Cineastas"
admin.site.index_title = "Cineastas"
admin.site.site_title = "Administracion Cineastas"

Cine/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class Genero(models.Model):
    genero = models.CharField(max_length=50)
    def __str__(self):
        return self.genero


class Idioma(models.Model):
    idioma = models.CharField(max_length=50)
    def __str__(self):
        return self.idioma


class Pelicula(models.Model):
    nombre = models.CharField(max_length=50)
    imagen = models.ImageField(upload_to="pelicula", blank=True, null=True)
    duracionMinutos = models.IntegerField(default=0, blank=True, null=True)
    genero = models.ManyToManyField(Genero)
    idioma = models.ManyToManyField(Idioma)

    def __str__(self):
        return self.nombre


class Cine(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='cines_propios')
    nombre = models.CharField(max_length=50)
    imagen = models.ImageField(upload_to="cine", blank=True, null=True)
    direccion = models.CharField(max_length=50)
    horariosInicio = models.TimeField()
    horariosFin = models.TimeField()
    estado = models.BooleanField(default=False)
    #usuariosadm = models.ManyToManyField(User, related_name='cines_administrados',blank=True, null=True)

    def __str__(self):
        return self.nombre


class Funcion(models.Model):
    cine = models.ForeignKey(Cine, on_delete=models.CASCADE)
    pelicula = models.ForeignKey(Pelicula, on_delete=models.CASCADE)
    estreno = models.BooleanField(default=True)
    dia = models.DateField(blank=True, null=True)
    horario = models.TimeField(blank=True, null=True)
    idioma = models.ForeignKey(Idioma, on_delete=models.CASCADE)
    subtitulo = models.BooleanField(default=False)
    votos = models.ManyToManyField(User, related_name='votos', blank=True)

    class Meta:
        unique_together = ('cine', 'pelicula', 'dia', 'horario', 'idioma', 'subtitulo')

    def total_votos(self):
        return self.votos.count()


class Comment(models.Model):
    pelicula = models.ForeignKey(Pelicula, on_delete=models.CASCADE, blank=True, null=True, related_name='comments')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    funcion = models.ForeignKey(Funcion, on_delete=models.CASCADE, blank=True, null=True)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='replies')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=True)
    cantidad_denuncia = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return self.text


class Denuncia(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    motivo = models.TextField()

    class Meta:
        unique_together = ('comment', 'usuario')

    def __str__(self):
        return self.motivo


class Megusta(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    pelicula = models.ForeignKey(Pelicula, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        unique_together = ('usuario', 'pelicula')

Cine/views.py
from datetime import date
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Cine, Pelicula, Funcion, Genero, Idioma, User, Comment, Denuncia, Megusta
from .forms import PeliculasForm, CineForm, GeneroForm, IdiomaForm, FuncionForm, CommentForm, DenunciaForm
from django.contrib.auth.decorators import permission_required
from django.contrib.admin.views.decorators import staff_member_required
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.http import JsonResponse
#serialzar rest
from rest_framework import viewsets, generics
from .serializers import GeneroSerializer, IdiomaSerializer, PeliculaSerializer
#para token
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.generic.edit import FormView
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm
from rest_framework.authtoken.models import Token
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.response import Response
from builtins import super


class GeneroList(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticated,)

    queryset = Genero.objects.all()
    serializer_class = GeneroSerializer
    # permission_classes = (IsAuthenticated,)
    # authentication_class = (TokenAuthentication,)


class GeneroDetail(generics.RetrieveAPIView):
    permission_classes = (IsAuthenticated,)

    queryset = Genero.objects.all()
    serializer_class = GeneroSerializer


class IdiomaList(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticated,)

    queryset = Idioma.objects.all()
    serializer_class = IdiomaSerializer
    # permission_classes = (IsAuthenticated,)
    # authentication_class = (TokenAuthentication,)


class IdiomaDetail(generics.RetrieveAPIView):
    permission_classes = (IsAuthenticated,)

    queryset = Idioma.objects.all()
    serializer_class = IdiomaSerializer


class PeliculaList(generics.ListCreateAPIView):
    permission_classes = (IsAuthenticated,)

    queryset = Pelicula.objects.all()
    serializer_class = PeliculaSerializer
    # permission_classes = (IsAuthenticated,)
    # authentication_class = (TokenAuthentication,)


class PeliculaDetail(generics.RetrieveAPIView):
    permission_classes = (IsAuthenticated,)

    queryset = Pelicula.objects.all()
    serializer_class = PeliculaSerializer


# class Login(FormView):
#     template_name = "login.html"
#     form_class = AuthenticationForm
#     success_url = reverse_lazy('api:genero_list')
#
#     @method_decorator(csrf_protect)
#     @method_decorator(never_cache)
#     def dispatch(self, request, *args, **kwargs):
#         if request.user.is_authenticated:
#             return HttpResponseRedirect(self.get_succes_url())
#         else:
#             return super(Login, self).dispatch(request, *args, **kwargs)
#
#     def form_valid(self, form):
#         user = authenticate(username=form.cleaned_data['username'],
#                             password=form.cleaned_data['password'])
#         token,_ = Token.objects.get_or_create(user=user)
#         if token:
#             login(self.request, form.get_user())
#             return super(Login, self).form_valid(form)
#
#
# class Logout(APIView):
#     def get(self, request, format=None):
#         request.user.auth_token.delete()
#         logout(request)
#         return Response(status=status.HTTP_200_OK)


def Home(request):
    cines = Cine.objects.filter(estado="True")
    peliculas_lista = Pelicula.objects.all()

    paginator_pelicula = Paginator(peliculas_lista, 6)
    page_pelicula = request.GET.get('page')
    peliculas = paginator_pelicula.get_page(page_pelicula)

    return render(request, 'home.html', {'cines': cines, 'peliculas': peliculas})


def About(request):
    return render(request, "about.html", {})


@login_required
def Administrar(request):
    return render(request, "administrar.html", {})


@login_required
def VotacionEstreno(request):
    return render(request, 'votacionestreno.html', {})


def MostrarCine(request, id):
    cine = Cine.objects.get(id=id)
    return render(request, 'mostrarcine.html', {'cine': cine})


def MostrarFunciones(request, id):
    cine = Cine.objects.get(id=id)
    listaFuncionesEstrenos = Funcion.objects.filter(cine=cine, estreno="True", dia__gt=date.today()).order_by('dia', 'horario')
    listaFunciones = Funcion.objects.filter(cine=cine, estreno="False", dia__gt=date.today()).order_by('dia', 'horario')
    listaTodas = Funcion.objects.filter(cine=cine, dia__gt=date.today()).order_by('dia', 'horario')

    paginator_pelicula = Paginator(listaTodas, 3)
    page_pelicula = request.GET.get('page')
    listaToda = paginator_pelicula.get_page(page_pelicula)

    paginator_pelicula = Paginator(listaFuncionesEstrenos, 3)
    page_pelicula = request.GET.get('page')
    listaFuncionesEstreno = paginator_pelicula.get_page(page_pelicula)

    paginator_pelicula = Paginator(listaFunciones, 3)
    page_pelicula = request.GET.get('page')
    listaFunciones = paginator_pelicula.get_page(page_pelicula)

    return render(request, 'mostrarfunciones.html', {'listaFunciones': listaFunciones,
                                                     'listaFuncionesEstreno': listaFuncionesEstreno,
                                                     'listaToda': listaToda,
                                                     'cine': cine})


def MostrarPeliculas(request, id):
    cine = Cine.objects.get(id=id)

    #funcionEstreno = Funcion.objects.filter(cine=cine, estreno="True", dia__gt=date.today())
    peliculaEstrenos= Pelicula.objects.filter(id__in=Funcion.objects.filter(cine=cine, estreno="True", dia__gt=date.today()).values("pelicula_id"))

    #funcionpelicula = Funcion.objects.filter(cine=cine, estreno="False", dia__gt=date.today())
    peliculas = Pelicula.objects.filter(id__in=Funcion.objects.filter(cine=cine, estreno="False", dia__gt=date.today()).values("pelicula_id"))

    paginator_pelicula = Paginator(peliculaEstrenos, 6)
    page_pelicula = request.GET.get('page')
    listaEstreno = paginator_pelicula.get_page(page_pelicula)

    paginator_pelicula = Paginator(peliculas, 6)
    page_pelicula = request.GET.get('page')
    listapelicula = paginator_pelicula.get_page(page_pelicula)

    return render(request, 'mostrarpeliculas.html', {'listaEstreno': listaEstreno,
                                                     'listapelicula': listapelicula,
                                                     'cine': cine, })


########################################### ADMINISTRAR PELICULA#################################################


@staff_member_required
def AdministarPelicula(request):
    peliculas = Pelicula.objects.all()
    return render(request, 'administrarpelicula.html', {'peliculas': peliculas})


@staff_member_required
def CrearPelicula(request):
    if request.method == 'POST':
        pelicula_form = PeliculasForm(request.POST, request.FILES)
        if pelicula_form.is_valid():
            pelicula_form.save()
            return redirect('administrarpelicula')
    else:
        pelicula_form = PeliculasForm()
    return render(request, 'crearpelicula.html', {'pelicula_form': pelicula_form})


@staff_member_required
def EditarPelicula(request, id):
    pelicula = Pelicula.objects.get(id=id)
    if request.method == 'GET':
        pelicula_form = PeliculasForm(instance=pelicula)
    else:
        pelicula_form = PeliculasForm(request.POST, instance=pelicula)
        if pelicula_form.is_valid():
            pelicula_form.save()
        return redirect('administrarpelicula')
    return render(request, 'crearpelicula.html', {'pelicula_form': pelicula_form})


@staff_member_required
def EliminarPelicula(request, id):
    pelicula = Pelicula.objects.get(id=id)
    pelicula.delete()
    return redirect('administrarpelicula')


########################################### ADMINISTRAR GENERO#################################################
@staff_member_required
def AdministarGenero(request):
    genero = Genero.objects.all()
    return render(request, 'administrargenero.html', {'genero': genero})


@staff_member_required
def CrearGenero(request):
    if request.method == 'POST':
        genero_form = GeneroForm(request.POST)
        if genero_form.is_valid():
            genero_form.save()
            return redirect('administrargenero')
    else:
        genero_form = GeneroForm()
    return render(request, 'creargenero.html', {'genero_form': genero_form})


@staff_member_required
def EditarGenero(request, id):
    genero = Genero.objects.get(id=id)
    if request.method == 'GET':
        genero_form = GeneroForm(instance=genero)
    else:
        genero_form = GeneroForm(request.POST, instance=genero)
        if genero_form.is_valid():
            genero_form.save()
        return redirect('administrargenero')
    return render(request, 'creargenero.html', {'genero_form': genero_form})


@staff_member_required
def EliminarGenero(request, id):
    genero = Genero.objects.get(id=id)
    genero.delete()
    return redirect('administrargenero')


########################################### ADMINISTRAR IDIOMA#################################################

@staff_member_required
def AdministarIdioma(request):
    idioma = Idioma.objects.all()
    return render(request, 'administraridioma.html', {'idioma': idioma})


@staff_member_required
def CrearIdioma(request):
    if request.method == 'POST':
        idioma_form = IdiomaForm(request.POST);
        #idioma_form.idioma = request.POST.get('idioma')

Cine/templates/administrar.html
{%extends 'base.html'%}

{% load staticfiles %}

{%block title%}Home{%endblock%}

{%block barra%}

<h1 class="my-4"></h1>
<div class="list-group">
    <a href="#" class="list-group-item list-group-item-action active bg-dark"> Administrar </a>
    <a href="{% url 'administrarcine' %}" class="list-group-item list-group-item-action">Administrar cine</a>
    <a href="{% url 'administrarfuncion' %}" class="list-group-item list-group-item-action">Administrar Funciones</a>
</div>

<h1 class="my-4"></h1>
{% if request.user.is_superuser or request.user.is_staff  %}
<div class="list-group">
    <a href="#" class="list-group-item list-group-item-action active bg-dark"> Administrar Staff </a>
    <a href="{% url 'administrarpelicula' %}" class="list-group-item list-group-item-action">Administrar peliculas</a>
    <a href="{% url 'administrargenero' %}" class="list-group-item list-group-item-action">Administrar genero</a>
    <a href="{% url 'administraridioma' %}" class="list-group-item list-group-item-action">Administrar idioma</a>
</div>
{% endif %}

<h1 class="my-4"></h1>
{% if request.user.is_superuser or request.user.is_staff %}
<div class="list-group">
    <a href="#" class="list-group-item list-group-item-action active bg-dark"> Administrar Super Usuario </a>
    <a href="{% url 'administrarDenunciaComentarios' %}" class="list-group-item list-group-item-action">Administrar denuncias</a>
</div>
{% endif %}



{%endblock barra%}

Cine/templates/administrarfuncion.html
{%extends 'base.html'%}

{% load staticfiles %}

{%block title%}Home{%endblock%}

{%block content%}

<h1 class="my-4"></h1>
<a class="btn btn-secondary" href="{% url 'crearfuncion' %}" role="button">Crear funcion</a>
<a class="btn btn-secondary" href="{% url 'administrar' %}" role="button">Volver</a>
<h1 class="my-4"></h1>
    {% if funciones %}
    <table id="tablefuncion" class="table table-striped table-bordered" >
        <thead>
            <tr>
                <th scope="col">Cine</th>
                <th scope="col">Pelicula</th>
                <th scope="col">Estreno</th>
                <th scope="col">Fecha</th>
                <th scope="col">Horario</th>
                <th scope="col">Idioma</th>
                <th scope="col">Subtitulo</th>
                <th scope="col">Acciones</th>

            </tr>
        </thead>
        <tbody>
            {% for fun in funciones%}
            <tr>
                <th scope="row">{{fun.cine}}</th>
                <th scope="row">{{fun.pelicula}}</th>
                <th scope="row">{{fun.estreno}}</th>
                <th scope="row">{{fun.dia}}</th>
                <th scope="row">{{fun.horario}}</th>
                <th scope="row">{{fun.idioma}}</th>
                <th scope="row">{{fun.subtitulo}}</th>
                <th scope="row">
                    <a href="{% url 'editarfuncion' fun.id %}">editar</a>
                    <a href="{% url 'eliminarfuncion' fun.id %}">eliminar</a>
                </th>
            </tr>
            {%endfor%}
        </tbody>
    </table>
    {%endif%}
{%endblock%}




{%block js%}
    <script>
        $(document).ready( function () {
            $('#tablefuncion').DataTable({
                language: {
                "sProcessing":     "Procesando...",
                "sLengthMenu":     "Mostrar _MENU_ registros",
                "sZeroRecords":    "No se encontraron resultados",
                "sEmptyTable":     "Ningún dato disponible en esta tabla",
                "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix":    "",
                "sSearch":         "Buscar:",
                "sUrl":            "",
                "sInfoThousands":  ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst":    "Primero",
                    "sLast":     "Último",
                    "sNext":     "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
                }
            });
        } );
    </script>
{%endblock js%}

Cine/templates/administraridioma.html
{%extends 'base.html'%}

{% load staticfiles %}

{%block title%}Home{%endblock%}

{%block content%}

<h1 class="my-4"></h1>
<a class="btn btn-secondary" href="{% url 'crearidioma' %}" role="button">Crear idioma</a>
<a class="btn btn-secondary" href="{% url 'administrar' %}" role="button">Volver</a>

<h1 class="my-4"></h1>
    {% if idioma %}
    <table id="tableidioma" class="table table-striped table-bordered" >
        <thead>
            <tr>
                <th scope="col">Idioma</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for idi in idioma%}
            <tr>
                <th scope="row">{{idi.idioma}}</th>
                <th scope="row">
                    <a href="{% url 'editaridioma' idi.id %}">editar</a>
                    <a href="{% url 'eliminaridioma' idi.id %}">eliminar</a>
                </th>
            </tr>
            {%endfor%}
        </tbody>
    </table>
    {%endif%}
{%endblock%}

{%block js%}
    <script>
        $(document).ready( function () {
            $('#tableidioma').DataTable({
                language: {
                "sProcessing":     "Procesando...",
                "sLengthMenu":     "Mostrar _MENU_ registros",
                "sZeroRecords":    "No se encontraron resultados",
                "sEmptyTable":     "Ningún dato disponible en esta tabla",
                "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix":    "",
                "sSearch":         "Buscar:",
                "sUrl":            "",
                "sInfoThousands":  ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst":    "Primero",
                    "sLast":     "Último",
                    "sNext":     "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
                }
            }
            );
        } );
    </script>
{%endblock js%}

Cine/templates/comments.html
<div class="container-fluid mt-2">
    <div class="form-group row">
        <form method="post" class="comment-form" action=".">
            {% csrf_token %}
            {{comment_form.as_p}}
            {% if request.user.is_authenticated %}
            <input type="submit" value="Submit" class="btn btn-outline-success">
            {%else%}
            <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
            {%endif%}
        </form>
    </div>
</div>

<p id="Cantidad">{{comments.count}} Comentario{{comments|pluralize}}</p>


{% for comment in comments %}
<blockquote class="blockquote">
    <p class="mb-0"><small>{{comment.text}}</small></p>
    <footer class="blockquote-footer">
        <small>Escrito por: <cite title="Source Title">{{comment.usuario|capfirst}}</cite>
            el {{comment.created_date}}
            {% if request.user.is_authenticated %}
            <a class="btn btn-danger" href="{% url 'denuncia' comment.id %}" role="button">Denunciar</a>
            {%endif%}
        </small>
        <button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sn">Reply</button>
    </footer>
</blockquote>

<div class="replied-comments container mt-2" style="display:none;">
    {% for reply in comment.replies.all %}
        {% if reply.approved_comment %}
        <blockquote class="blockquote">
            <p class="mb-0"><small>{{reply.text}}</small></p>
            <footer class="blockquote-footer">
                <small>Escrito por: <cite
                        title="Source Title">{{reply.usuario|capfirst}}</cite> el {{com.created_date}}
                    {% if request.user.is_authenticated %}
                    <a class="btn btn-danger" href="{% url 'denuncia' reply.id %}" role="button">Denunciar</a>
                    {%endif%}
                </small>
            </footer>
        </blockquote>
        {%endif%}
    {%endfor%}



    <div class="form-group row">
        <form method="post" class="reply-form" action=".">
            {% csrf_token %}
            <input type="hidden" name="reply_id" value="{{comment.id}}">
            {{comment_form.as_p}}
            {% if request.user.is_authenticated %}
            <input type="submit" value="Submit" class="btn btn-outline-success">
            {%else%}
            <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
            {%endif%}
        </form>
    </div>

</div>
{% endfor %}

Cine/templates/crearcine.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load staticfiles %}

{%block content%}
    <div class ='row justify-content-center'>
        <div class='col-md-6 col-md-offset-3'>
            <h1 class="my-4"></h1>
            <form method="POST" enctype="multipart/form-data">
            {%csrf_token%}
            {{cine_form|crispy}}
            <input class="btn btn-secondary" type="submit" value="Crear">
            <a class="btn btn-secondary" type="submit" href="{% url 'administrarcine' %}" role="button">Volver</a>
            </form>
        </div>
    </div>
{%endblock%}

Cine/templates/crearfuncion.html
{%extends 'base.html'%}

{% load crispy_forms_tags %}

{% load staticfiles %}
{%block meta%}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" rel="stylesheet" />
    {{ form.media.css }}
{%endblock%}

{%block content%}


    <div class ='row justify-content-center'>
        <div class='col-md-6 col-md-offset-3'>
            <h1 class="my-4"></h1>
            <form method="POST">
                {%csrf_token%}
                {{funcion_form|crispy}}
                <input class="btn btn-primary" type="submit" value="Crear">
                <a class="btn btn-primary" href="{% url 'administrarfuncion' %}" role="button">Volver</a>
            </form>
        </div>
    </div>
{%endblock%}
{%block js%}
    {{ form.media.js }}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>

    <script>
        $(document).ready(function() {
            $('#id_pelicula').select2();
        });
    </script>
{%endblock js%}